interfaces:
  - port: "gi0/0"
    description: "*MGMT INTERFACE*"
    ipv4addr: "172.17.82.54"
    ipv4mask: "255.255.255.0"

  - port: "gi0/2"
    description: "*TO:Gi0/1 - IOS-R6*"
    ipv4addr: "10.0.6.4"
    ipv4mask: "255.255.255.0"

  - port: "gi0/3"
    description: "*TO:Gi0/3 - IOS-R5*"
    ipv4addr: "10.0.4.4"
    ipv4mask: "255.255.255.0"

nameservers:
  - ip: "208.67.220.220"
  - ip: "208.67.222.222"
