interfaces:
  GigabitEthernet0/0:
    description: "*MGMT INTERFACE*"
    vrfname: "MGMT"
    ipv4addr: "172.17.82.50"
    ipv4mask: "255.255.255.0"
    urpfon: true
    activate: true
    ospf_process_id:
    ospf_area:
    ospf_make_passive: true
    ospf_network_type:

  GigabitEthernet0/1:
    description: "*TO:Gi0/1 - IOS-R2*"
    vrfname:
    ipv4addr: "10.0.1.1"
    ipv4mask: "255.255.255.0"
    urpfon: false
    activate: true
    ospf_process_id: "1"
    ospf_area: "0"
    ospf_make_passive: false
    ospf_network_type: "point-to-point"

  GigabitEthernet0/2:
    description: "AVAILABLE"
    vrfname:
    ipv4addr:
    ipv4mask:
    urpfon: false
    activate: false
    ospf_process_id:
    ospf_area:
    ospf_make_passive: true
    ospf_network_type:

  GigabitEthernet0/3:
    description: "AVAILABLE"
    vrfname:
    ipv4addr:
    ipv4mask:
    urpfon: false
    activate: false
    ospf_process_id:
    ospf_area:
    ospf_make_passive: true
    ospf_network_type: "point-to-point"

  Loopback0:
    description: "*LOOPBACK-{{ inventory_hostname }}*"
    vrfname:
    ipv4addr: "1.1.1.1"
    ipv4mask: "255.255.255.255"
    urpfon: false
    activate: true
    ospf_process_id: "1"
    ospf_area: "0"
    ospf_make_passive: true
    ospf_network_type: "point-to-point"

ospf:
  processes:
  - log_adjacency_changes:
      detail: true
    passive_interfaces:
      default: true
    process_id: "1" # hardcoded this because I couldn't find a better way of doing it yet.
    router_id: "{{ interfaces['Loopback0'].ipv4addr }}"

nameservers:
  - ip: "208.67.220.220"
  - ip: "208.67.222.222"