interfaces:
  - port: "gi0/0"
    description: "*MGMT INTERFACE*"
    ipv4addr: "172.17.82.51"
    ipv4mask: "255.255.255.0"

  - port: "gi0/1"
    description: "*TO:Gi0/1 - IOS-R1*"
    ipv4addr: "10.0.0.2"
    ipv4mask: "255.255.255.0"