interfaces:
  gi0/0:
    description: "*MGMT INTERFACE*"
    vrfname: "MGMT"
    ipv4addr: "172.17.82.54"
    ipv4mask: "255.255.255.0"
    urpfon: true
    activate: true

  gi0/1:
    description: "*TO:Gi0/0/0/0 - IOSXR-R1*"
    vrfname:
    ipv4addr: "10.10.4.4"
    ipv4mask: "255.255.255.0"
    urpfon: false
    activate: true

  gi0/2:
    description: "*TO:Gi0/1 - IOS-R6*"
    vrfname:
    ipv4addr: "10.0.6.4"
    ipv4mask: "255.255.255.0"
    urpfon: false
    activate: true

  gi0/3:
    description: "*TO:Gi0/3 - IOS-R5*"
    vrfname:
    ipv4addr: "10.0.4.4"
    ipv4mask: "255.255.255.0"
    urpfon: false
    activate: true
  
  lo0:
    description: "*LOOPBACK-{{ inventory_hostname }}*"
    vrfname:
    ipv4addr: "4.4.4.4"
    ipv4mask: "255.255.255.255"
    urpfon: false
    activate: true

nameservers:
  - ip: "208.67.220.220"
  - ip: "208.67.222.222"
