interfaces:
  gi0/0:
    description: "*MGMT INTERFACE*"
    vrfname: "MGMT"
    ipv4addr: "172.17.82.56"
    ipv4mask: "255.255.255.0"

  gi0/1:
    description: "*TO:Gi0/2 - IOS-R4*"
    vrfname:
    ipv4addr: "10.0.6.6"
    ipv4mask: "255.255.255.0"

nameservers:
  - ip: "208.67.220.220"
  - ip: "208.67.222.222"
