interfaces:
  MgmtEth0/0/CPU0/0:
    description: "*MGMT INTERFACE*"
    vrfname: "MGMT"
    ipv4addr: "172.17.82.53"
    ipv4mask: "255.255.255.0"
    activate: true
    ospf_process_id:
    ospf_area:
    ospf_make_passive: true
    ospf_network_type:

  GigabitEthernet0/0/0/0:
    description: "*TO:Gi0/3 - IOS-R2*"
    vrfname:
    ipv4addr: "10.10.2.1"
    ipv4mask: "255.255.255.0"
    activate: true
    ospf_process_id: "DEFAULT"
    ospf_area: "0"
    ospf_make_passive: false
    ospf_network_type: "point-to-point"

  GigabitEthernet0/0/0/1:
    description: "*TO:Gi0/0/0/1 - IOSXR-R2*"
    vrfname:
    ipv4addr: "10.10.1.1"
    ipv4mask: "255.255.255.0"
    activate: true
    ospf_process_id: "DEFAULT"
    ospf_area: "0"
    ospf_make_passive: false
    ospf_network_type: "point-to-point"

  GigabitEthernet0/0/0/2:
    description: "AVAILABLE"
    vrfname:
    ipv4addr:
    ipv4mask:
    activate: false
    ospf_process_id:
    ospf_area:
    ospf_make_passive: true
    ospf_network_type:

  Loopback0:
    description: "*LOOPBACK-{{ inventory_hostname }}*"
    vrfname:
    ipv4addr: "10.10.10.1"
    ipv4mask: "255.255.255.0"
    activate: true
    ospf_process_id: "DEFAULT"
    ospf_area: "0"
    ospf_make_passive: true
    ospf_network_type:

ospf:
  processes:
    - process_id: "DEFAULT"
      router_id: "{{ interfaces['Loopback0'].ipv4addr }}"
