- name: "PLAY 1 - Configure OSPFv2 on XRv routers"
  hosts: ios_xr  # THIS WILL REFER TO THE HOST/GROUP THAT THIS PLAY IS TARGETING
  connection: network_cli  # FOR NETWORK DEVICES THE CONNECTION WILL BE 'network_cli'
  tasks:
    - name: "TASK 1: Configure OSPFv2 process for XRv router"
      iosxr_ospfv2:
        config: "{{ ospf }}"  # this variable is taken from the 'host_vars'/ device file 'ospf:' setion
        state: merged
      register: cli_ospf_result

    - name: "TASK 2: Display output of Task 1"
      debug:
        msg: "{{ cli_ospf_result }}"

    - name: "TASK 3: Configure OSPFv2 inerface on XRv using the iosxr_ospf_interfaces module from templates/iosxr_ospf_config.j2"
      cli_config:
        # Using the lookup plugin to retrieve from ../templates/iosxr_ospf__config.j2
        config: "{{ lookup('template', '../templates/iosxr_ospf_config.j2') }}"
        commit: true
        commit_comment: "Configured by Ansible"
      notify: config_changed  # a conditional that notifies the handler below if the configuration has changed.
      register: cli_result

  handlers:
    - name: "TASK 4: Display output of Task 3 if configure has changed"
      listen: config_changed  # If the notify sends then config_changed then run debug.msg below
      debug:
        msg: "{{ cli_result }}"
